//! Public, deterministic **operation-script fuzz harness** for the input/backtracking machinery.
//!
//! A fuzz case drives arbitrary token streams through the crate's public input operations — consume
//! and look-ahead, the `sync` family, `attempt`/`try_attempt`, the
//! [`Transaction`](crate::Transaction) and
//! [`StackedTransaction`](crate::StackedTransaction) guards with their savepoints, the
//! [`ParseState`](crate::ParseState) session points, and the [`Partial`](crate::input::Partial)
//! chunking surface — and checks the machinery's **documented laws** after every operation (see the
//! oracle list below). It is a public, feature-gated module that runs as ordinary `#[test]`s on
//! stable Rust; there is no dependency on a nightly fuzzer.
//!
//! # The anti-lag guarantee (why this exists)
//!
//! The crate's earlier property tests caught nothing across a 21-round adversarial review because
//! their hand-maintained operation alphabet always lagged the real surface — every new operation
//! landed *after* the alphabet froze. This harness is structured so the alphabet **cannot** lag:
//! the alphabet is enumerated in exactly one place, [`Op`](crate::fuzz::Op), generated by a
//! single-list macro; a
//! wildcard-free classifier and per-executor `match`es make an unhandled new op a **compile error**;
//! a compile-time census (`OP_SURFACE_CENSUS`) trips the instant the alphabet changes size; and the
//! corpus coverage test fails unless every declared op is actually *executed*. See
//! [`Op`](crate::fuzz::Op) and
//! `src/fuzz/ops.rs` for the full mechanism and its one un-mechanizable residual.
//!
//! # Oracles
//!
//! Checked after every operation, against a closed-form shadow model (a straight re-lex reference
//! plus a stack model of guard/savepoint/session nesting):
//!
//! 1. **Faithfulness** — a returned token equals the straight-lex reference; the committed stream
//!    only ever extends and matches the reference at every quiescent point.
//! 2. **No-trace** — a declined `attempt`, a rolled-back guard, and a no-match
//!    `sync_through`/`sync_balanced` leave the cursor *and* the emission count exactly as they were.
//! 3. **LIFO/pin** — a guard, savepoint, or session rollback restores the exact begin-point state.
//! 4. **Chunked equivalence** — reassembling partial-mode chunk prefixes reproduces the single-shot
//!    parse (`set_final`, frontier holdback, the `Incomplete` channel).
//! 5. **Termination** — every generated script is bounded and terminates.
//! 6. **No panic** — a debug build reaching any assertion (including the machinery's own witness
//!    asserts) is a finding.
//!
//! # Reproduce-with-seed workflow
//!
//! Every case is a pure function of its `u64` seed — there is no external entropy. When the corpus
//! test reports a failing seed `N`, reproduce it in isolation with:
//!
//! ```no_run
//! use tokit::fuzz::{Case, run_case};
//! // Re-run exactly the case that failed; the panic message names the violated oracle.
//! run_case(Case::from_seed(0xBAD_5EED));
//! ```
//!
//! The default corpus (`Case::from_seed(0..256)`) runs as part of the normal test suite; a longer
//! `#[ignore]`d run is available for manual deep sweeps. On a failure, minimize by re-running the
//! seed and truncating (the harness's scripts are short by construction).

use std::vec::Vec;

mod consume;
mod fixtures;
mod ops;
mod partial;
mod rng;
mod session;

pub use ops::{Coverage, EXPECTED_OP_COUNT, Op, all_labels};

use rng::Rng;

/// The default in-crate corpus size: seeds `0..DEFAULT_CORPUS` run as part of the normal suite.
pub const DEFAULT_CORPUS: u64 = 256;

/// The seeds excluded from the default corpus because they reproduce a *known, triaged* machinery
/// finding (a fuzz wave records findings; it does not fix the machinery). Empty means no finding is
/// currently outstanding. Each entry MUST carry a comment naming the finding and its violated
/// oracle, so a later machinery fix can re-enable it.
const EXCLUDED_SEEDS: &[u64] = &[
  // (no outstanding findings)
];

/// A single fuzz case, fully determined by its `u64` seed.
///
/// The seed selects the case kind (a consume-tree case over the backtracking guards, a session-
/// point case, or a partial-input chunking case), the synthetic token stream, and the operation
/// script — all deterministically, so a run reproduces exactly from its seed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Case {
  seed: u64,
}

impl Case {
  /// Builds the case for `seed`.
  #[must_use]
  pub const fn from_seed(seed: u64) -> Self {
    Self { seed }
  }

  /// The seed this case reproduces from.
  #[must_use]
  pub const fn seed(self) -> u64 {
    self.seed
  }
}

/// Runs one case to completion, returning which [`Op`]s it exercised.
///
/// # Panics
///
/// Panics — a *finding* — the moment an oracle is violated, with a message naming the violated law.
/// Reproduce the panic in isolation with `run_case(Case::from_seed(seed))`.
///
/// # Example
///
/// ```
/// use tokit::fuzz::{Case, run_case};
///
/// // Deterministic: the same seed always drives the same case and passes the same oracles.
/// let a = run_case(Case::from_seed(7));
/// let b = run_case(Case::from_seed(7));
/// assert_eq!(a.missing(), b.missing());
/// ```
pub fn run_case(case: Case) -> Coverage {
  let mut rng = Rng::new(case.seed);
  let mut cov = Coverage::new();
  match rng.below(5) {
    // Weighted toward the consume tree, which owns most of the alphabet.
    0..=2 => {
      let src = gen_stream(&mut rng, /*allow_errors*/ false);
      let script = consume::gen_seq(&mut rng, 0);
      consume::run(&src, &script, &mut cov, case.seed ^ 0xE0EC_0DE5);
    }
    3 => {
      let src = gen_stream(&mut rng, false);
      session::run(&src, case.seed, &mut cov);
    }
    _ => {
      let src = gen_stream(&mut rng, /*allow_errors*/ true);
      partial::run(&src, case.seed, &mut cov);
    }
  }
  cov
}

/// Runs every case in `seeds`, returning the aggregate coverage. Panics on the first finding.
///
/// ```
/// use tokit::fuzz::run_seeds;
/// let cov = run_seeds(0..64);
/// // A short range need not cover the whole alphabet; the default corpus does.
/// let _ = cov.missing();
/// ```
pub fn run_seeds(seeds: core::ops::Range<u64>) -> Coverage {
  let mut cov = Coverage::new();
  for seed in seeds {
    if EXCLUDED_SEEDS.contains(&seed) {
      continue;
    }
    let c = run_case(Case::from_seed(seed));
    cov.merge(&c);
  }
  cov
}

// ── Synthetic token-stream generation ────────────────────────────────────────────────────────────

/// Generates a synthetic token stream: a short byte string over a palette weighted toward words
/// with a healthy sprinkling of delimiters and separators (so `sync_balanced` nests) and, when
/// `allow_errors`, lexer-error bytes.
fn gen_stream(rng: &mut Rng, allow_errors: bool) -> Vec<u8> {
  let n = rng.below(40);
  (0..n).map(|_| gen_byte(rng, allow_errors)).collect()
}

/// One palette byte.
fn gen_byte(rng: &mut Rng, allow_errors: bool) -> u8 {
  if allow_errors && rng.chance(1, 6) {
    // A lexer-error byte (0xE0..=0xFF).
    return 0xE0u8.wrapping_add(rng.below(0x20) as u8);
  }
  match rng.below(10) {
    0 => *b"([{".get(rng.below(3)).unwrap(),
    1 => *b")]}".get(rng.below(3)).unwrap(),
    2 => *b";,".get(rng.below(2)).unwrap(),
    _ => b'a' + rng.below(26) as u8,
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  /// The alphabet census is intact: exactly [`EXPECTED_OP_COUNT`] operations, all labels distinct.
  /// (The size is also a compile-time `const _` assert in `ops.rs`; this gives a runtime message.)
  #[test]
  fn op_alphabet_census() {
    assert_eq!(
      Op::COUNT,
      EXPECTED_OP_COUNT,
      "OP_SURFACE_CENSUS drift: the fuzz Op alphabet changed size (grep OP_SURFACE_CENSUS)"
    );
    let mut labels = all_labels();
    labels.sort_unstable();
    labels.dedup();
    assert_eq!(labels.len(), Op::COUNT, "two Op variants share a label");
  }

  /// The default corpus passes every oracle AND exercises **every** operation in the alphabet. The
  /// coverage half is the runtime anti-lag prod: a declared-but-unfuzzed op fails here, naming
  /// itself, so a new alphabet entry cannot sit un-exercised.
  #[test]
  fn corpus_passes_and_covers_every_op() {
    let cov = run_seeds(0..DEFAULT_CORPUS);
    let missing = cov.missing();
    assert!(
      missing.is_empty(),
      "the default corpus (0..{DEFAULT_CORPUS}) did not exercise every Op: missing {:?}. \
       Widen the corpus or teach a generator to emit these (grep OP_SURFACE_CENSUS).",
      missing.iter().map(|op| op.label()).collect::<Vec<_>>()
    );
  }

  /// A deeper manual sweep. Ignored by default (part of neither CI nor the normal suite); run with
  /// `cargo test --features fuzz -- --ignored fuzz_deep_run`.
  #[test]
  #[ignore = "long-running manual deep fuzz sweep"]
  fn fuzz_deep_run() {
    let cov = run_seeds(0..50_000);
    assert!(
      cov.is_complete(),
      "deep run failed to cover the alphabet: {:?}",
      cov.missing()
    );
  }
}
