//! The operation alphabet — **the one place** the fuzz harness enumerates the public
//! input-machinery surface, plus the anti-lag machinery that keeps it from silently falling behind
//! that surface.
//!
//! # Why this is centralized (the 21-round lesson)
//!
//! The crate's earlier property tests caught nothing because their hand-maintained alphabet always
//! lagged the real surface: every new operation (savepoints, `sync_balanced`, session points,
//! partial mode) landed *after* the alphabet froze. This module structures the alphabet so it
//! **cannot** lag, through three interlocking mechanisms:
//!
//! 1. **One source list.** The `define_ops!` macro expands a single list into the [`Op`] enum, the
//!    [`Op::ALL`] table, [`Op::COUNT`], and the exhaustive [`Op::label`] classifier at once, so the
//!    enum and its table can never diverge.
//! 2. **A compile-time exhaustiveness prod.** [`Op::label`] is a wildcard-free `match`, and every
//!    executor dispatches on [`Op`] the same way: adding a variant that no arm handles is a
//!    **compile error**, and renaming/removing a covered method breaks the arm that invokes it.
//! 3. **A runtime coverage prod.** The [`OP_SURFACE_CENSUS`](EXPECTED_OP_COUNT) const-assert trips
//!    the instant the alphabet changes size, and the corpus coverage test
//!    (`corpus_passes_and_covers_every_op`) fails unless the default seed corpus actually
//!    *executes* every variant — a declared-but-unfuzzed op is caught, not merely a declared one.
//!
//! The only step stable Rust cannot mechanize is *noticing a brand-new public method exists* (Rust
//! has no method reflection). That residual is anchored by the greppable `OP_SURFACE_CENSUS`
//! census marker: the number a reviewer must consciously bump sits beside a checklist naming every
//! wiring step, and `grep OP_SURFACE_CENSUS` finds the marker from anywhere in the tree. See the
//! [module docs](crate::fuzz) for the full posture.

use std::vec::Vec;

/// Expands one operation list into the [`Op`] enum, its [`Op::ALL`] table, [`Op::COUNT`], and the
/// exhaustive [`Op::label`] classifier — so the alphabet is defined exactly once.
macro_rules! define_ops {
  ($( #[doc = $doc:literal] $variant:ident => $label:literal ),+ $(,)?) => {
    /// One operation of the public input-machinery surface — the fuzz alphabet.
    ///
    /// Each variant maps to a real public method (or a documented outcome path of one). The list is
    /// generated by `define_ops!`; to extend the surface, add a line there and honor the
    /// `OP_SURFACE_CENSUS` checklist. See the [module docs](crate::fuzz).
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub enum Op {
      $( #[doc = $doc] $variant ),+
    }

    impl Op {
      /// Every operation, in declaration order — the alphabet the generators sample and the
      /// coverage test iterates.
      pub const ALL: &'static [Op] = &[ $( Op::$variant ),+ ];

      /// The number of operations in the alphabet — the census.
      pub const COUNT: usize = Op::ALL.len();

      /// A stable, human-readable label for reports and coverage messages. This wildcard-free
      /// `match` is the compile-time exhaustiveness prod: a new variant that is not labelled here
      /// fails to compile.
      #[must_use]
      pub const fn label(self) -> &'static str {
        match self {
          $( Op::$variant => $label ),+
        }
      }
    }
  };
}

define_ops! {
  /// `InputRef::next` — advance one token.
  Next => "next",
  /// `InputRef::peek_one` — look ahead one token without consuming.
  PeekOne => "peek_one",
  /// `InputRef::peek::<W>` — fill a multi-token look-ahead window.
  Peek => "peek",
  /// `InputRef::try_expect(pred)` where `pred` matches the next token (consumes it).
  TryExpectHit => "try_expect(hit)",
  /// `InputRef::try_expect(pred)` where `pred` never matches (leaves the token).
  TryExpectMiss => "try_expect(miss)",
  /// `InputRef::try_expect_map` — map-and-consume a matching token.
  TryExpectMap => "try_expect_map",
  /// `InputRef::try_expect_and_then` — fallibly map-and-consume a matching token.
  TryExpectAndThen => "try_expect_and_then",
  /// `InputRef::skip_while(pred)` — drop a run of matching tokens without reporting them.
  SkipWhile => "skip_while",
  /// `InputRef::sync_to(pred)` — skip-and-report up to (not through) a sync token.
  SyncTo => "sync_to",
  /// `InputRef::sync_through(pred)` — skip-and-report through a sync token.
  SyncThrough => "sync_through",
  /// `InputRef::sync_balanced(class, pred)` — nesting-aware skip to a depth-0 sync token.
  SyncBalanced => "sync_balanced",
  /// `InputRef::is_eoi` — end-of-input query.
  IsEoi => "is_eoi",
  /// `Input::seal` / `InputRef::is_final` — the partial-input finality world fact: monotone, and driver-only (a handle can READ it; nothing but the owning input can write it).
  Seal => "seal",
  /// `InputRef::attempt(|_| Some(..))` — a closure attempt whose progress is kept.
  AttemptCommit => "attempt(commit)",
  /// `InputRef::attempt(|_| None)` — a closure attempt that declines and rolls back.
  AttemptDecline => "attempt(decline)",
  /// `InputRef::try_attempt(|_| Ok(..))` — a fallible attempt whose progress is kept.
  TryAttemptOk => "try_attempt(ok)",
  /// `InputRef::try_attempt(|_| Err(..))` — a fallible attempt that errors and rolls back.
  TryAttemptErr => "try_attempt(err)",
  /// `InputRef::begin` + `Transaction::commit` — a guard committed explicitly.
  TxnCommit => "transaction.commit",
  /// `InputRef::begin` + `Transaction::rollback` — a guard rolled back explicitly.
  TxnRollback => "transaction.rollback",
  /// `InputRef::begin` + drop — a `Rollback`-policy guard rolled back on drop.
  TxnDropRollback => "transaction.drop(rollback)",
  /// `InputRef::begin_with::<Commit>` + drop — a `Commit`-policy guard kept on drop.
  TxnDropCommit => "transaction.drop(commit)",
  /// `InputRef::begin_stacked` + `StackedTransaction::commit`.
  StackedCommit => "stacked.commit",
  /// `InputRef::begin_stacked` + `StackedTransaction::rollback`.
  StackedRollback => "stacked.rollback",
  /// `InputRef::begin_stacked_with::<Commit>` + drop — kept on drop.
  StackedDropCommit => "stacked.drop(commit)",
  /// `StackedTransaction::savepoint` — mark a nested fallback point.
  Savepoint => "savepoint",
  /// `StackedTransaction::rollback_to` — roll back to a live savepoint, keeping it.
  RollbackToSavepoint => "rollback_to",
  /// `StackedTransaction::release` — forget savepoints, keeping progress.
  ReleaseSavepoint => "release",
  /// `InputRef::begin_point` + `commit_point` — a session point kept.
  SessionCommit => "session.commit_point",
  /// `InputRef::begin_point` + `rollback_point` — a session point rolled back.
  SessionRollback => "session.rollback_point",
  /// `InputRef::begin_point` + drop the handle — a session point abandoned, settled by neither verb: the handle's `Drop` releases its pin while keeping its progress.
  SessionAbandon => "session.abandon(drop)",
}

/// OP_SURFACE_CENSUS — the number of public input-machinery operations the fuzz alphabet covers.
///
/// This is the ONE number a reviewer must consciously change when the surface moves. Bump it, and
/// in the **same** commit: add the `define_ops!` line, wire the op into a generator so the coverage
/// test exercises it, add its executor arm, and drop a `# Fuzz coverage` note in the op-adding
/// module's contract docs pointing here. `grep OP_SURFACE_CENSUS` finds every anchor.
pub const EXPECTED_OP_COUNT: usize = 30;

// Compile-time census tripwire: the alphabet cannot change size without this failing to compile at
// a named location, forcing the checklist above.
const _: () = assert!(
  Op::COUNT == EXPECTED_OP_COUNT,
  "OP_SURFACE_CENSUS drift: the fuzz `Op` alphabet changed size. Update EXPECTED_OP_COUNT and, in \
   the same commit, wire the new operation into a generator + an executor arm (grep OP_SURFACE_CENSUS)."
);

/// Which operations each executor is responsible for exercising — used only to make the coverage
/// test's diagnostics precise (it never gates dispatch, which is the executors' own exhaustive
/// matches).
impl Op {
  /// The index of this op in [`Op::ALL`].
  #[must_use]
  pub fn index(self) -> usize {
    Op::ALL
      .iter()
      .position(|&o| o == self)
      .expect("every Op is in Op::ALL by construction of define_ops!")
  }
}

/// A tally of which [`Op`]s a run actually executed — the runtime half of the anti-lag guarantee.
#[derive(Debug, Clone)]
pub struct Coverage {
  seen: [bool; Op::COUNT],
}

impl Default for Coverage {
  fn default() -> Self {
    Self::new()
  }
}

impl Coverage {
  /// An empty tally.
  #[must_use]
  pub const fn new() -> Self {
    Self {
      seen: [false; Op::COUNT],
    }
  }

  /// Records that `op` executed.
  #[inline]
  pub fn mark(&mut self, op: Op) {
    self.seen[op.index()] = true;
  }

  /// Folds another tally into this one (for aggregating across a corpus).
  pub fn merge(&mut self, other: &Coverage) {
    for (dst, src) in self.seen.iter_mut().zip(other.seen.iter()) {
      *dst |= *src;
    }
  }

  /// The operations not yet executed — empty means the alphabet is fully exercised.
  #[must_use]
  pub fn missing(&self) -> Vec<Op> {
    Op::ALL
      .iter()
      .enumerate()
      .filter(|(i, _)| !self.seen[*i])
      .map(|(_, &op)| op)
      .collect()
  }

  /// Whether every operation has executed.
  #[must_use]
  pub fn is_complete(&self) -> bool {
    self.seen.iter().all(|&s| s)
  }
}

/// The labels of every operation, for reports.
#[must_use]
pub fn all_labels() -> Vec<&'static str> {
  Op::ALL.iter().map(|op| op.label()).collect()
}
